#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f rRISCV.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace rRISCV.sv --exe testbench.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VrRISCV.mk VrRISCV

#run executable simulation file
obj_dir/VrRISCV
