#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f RISCV.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace RISCV.sv --exe testbench.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRISCV.mk VRISCV

#run executable simulation file
obj_dir/VRISCV
